versions:
  nessie: 0.5.1
  iceberg: 0.11.1

python_dependencies:
  pynessie: 0.5.1
  findspark: 1.4.2
  pyspark: 3.0.2

spark:
  tarball: https://downloads.apache.org/spark/spark-3.0.2/spark-3.0.2-bin-hadoop2.7.tgz

#uris:
#  nessie_native_image_binary:
#  nessie_docker_container:
